const fs = require('fs')
const path = require('path')

const pkg = require('../package.json')
const outPath = path.resolve(__dirname, '../src/client_version.ts')
const content = `// GENERATED SOURCE -- DO NOT EDIT!!\n// This file is generated by npm scripts\n\nexport const OMEGA_EDIT_CLIENT_VERSION = '${pkg.version}'\n`
fs.writeFileSync(outPath, content)

// copy license into package root for publishing
const licenseSrc = path.resolve(__dirname, '../../../LICENSE.txt')
const licenseDst = path.resolve(__dirname, '../LICENSE.txt')
fs.copyFileSync(licenseSrc, licenseDst)
